fix: Add missing fileType field in ProjectsStorageController site survey upload
The ProjectsStorageController was missing the fileType field when creating
SiteSurveyData, which was causing Hibernate parameter binding errors.

This fixes the database error:
ERROR: column "excel_file" is of type bytea but expression is of type bigint